### ISSUE TITLE
This doesn't work for U2F users.

### ISSUE THREAD

**Issue by OllieJC** [alphagov/gds-pre-commit#28]
https://github.com/alphagov/gds-pre-commit/blob/0a134f65d13c05e99a8026a2259fa54917bb95d3/register.py#L41

I don't have OTP.

**Comment by danjoneslf** [comment]
I can't fix this unless I have a YubiKey which I don't. @OllieJC - Aaron tested getting an OTP code with his YubiKey - Can you suggest an alternative implementation that would work for you?

**Comment by OllieJC** [comment]
<https://developer.github.com/v3/auth/#working-with-two-factor-authentication>:
```Deprecation Notice: GitHub will discontinue password authentication to the API. You must now authenticate to the GitHub API with an API token, such as an OAuth access token, GitHub App installation access token, or personal access token, depending on what you need to do with the token. Password authentication to the API will be removed on November 13, 2020. For more information, including scheduled brownouts, see the blog post.```

The API doesn't support [U2F](https://github.blog/2017-07-20-soft-u2f/), Yubikeys support OTP and U2F. A lot of users use U2F and we've been advocating its use.

I'd suggest using the GitHub web auth flow and get the users to paste a token into the CLI: https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/#web-application-flow
So have the CLI warn them it'll open a browser to copy/paste a code, get the CLI to open/request GitHub user profile: `https://github.com/login/oauth/authorize` (with required params), they get a token displayed in their browser, paste into CLI, CLI does _thing_.

**Comment by 0atman** [comment]
Perhaps this is an indication we should sidestep the issue with a simpler registration procedure? https://github.com/alphagov/gds-pre-commit/issues/27

**Comment by akinnane** [comment]
These two other PR's fix / workaround the authentication problem. I think the sheets based approach is simplest while being slightly more open to abuse, but I think it is within acceptable tolerances.
