### ISSUE TITLE
 Non-ASCII character '\xe2' in file .. on line 10

### ISSUE THREAD

**Issue by detnon** [alphagov/gds-pre-commit#29]
Initialy had this error which was resolved by removing the emojis in the install file:
 ~ ~/.gds-pre-commit/install.py
  File "/Users/jonmichaelpitt/.gds-pre-commit/install.py", line 10
SyntaxError: Non-ASCII character '\xe2' in file /Users/jonmichaelpitt/.gds-pre-commit/install.py on line 10, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
➜  ~ python --version 
Python 3.7.5

**Comment by 0atman** [comment]
This should be fixed in #30 @detnon could you try again with john? The install is idempotent,it will work fine if he deletes the .gds-pre-commit folder and runs the quick install instructions again

**Comment by detnon** [comment]
Issue resolved in #30
