### ISSUE TITLE
Relies on a `python` binary

### ISSUE THREAD

**Issue by Krenair** [alphagov/gds-pre-commit#60]
My system has no `python`, it has only `python3`. Therefore I couldn't `./install.py`, I had to `python3 install.py` - and that went fine, until I wanted to commit something and I found one of the hooks now expects a `python` binary:
```
$ git commit --allow-empty
/usr/bin/env: ‘python’: No such file or directory
```

I've removed its line from my ~/.gitconfig.

**Comment by 0atman** [comment]
Thanks for reporting. That's very annoying. Apologies this happened - covid killed this project last quarter, we've prioritised it again this quarter! :ok_hand:

**Comment by 0atman** [comment]
@Krenair We're thinking of tweaking our instructions and scripts to allow the user to run them, as you did, by invoking them with their version of python, that way we empower the user to choose the right python exe. What do you think?
```
python install.py
```
rather than
```
./install.py
```

**Comment by 0atman** [comment]
We'll have to do a bit of work with the hook itself, to avoid your second problem

**Comment by Krenair** [comment]
`python` is not a thing on my system - only `python3`. I would just change the shebang to use python3.

But this issue is mainly about the hook itself.

**Comment by 0atman** [comment]
closing due to the new scope of this project (see readme)
