### ISSUE TITLE
'usage' guide to main readme

### ISSUE THREAD

**Issue by pritchyspritch** [alphagov/gds-pre-commit#65]
David McDonald  6 days ago
Also for some more feedback I'd encourage the 'usage' guide which is linked to at the bottom of the readme to be more prominent and maybe not be a separate part of the readme. I don't think I'd consider it further reading, I'd consider it fairly essential in me getting set up

**Comment by katstevens** [comment]
Could we also add a note to the Usage guide that the `--exclude-files` argument is a regex, maybe with an example of excluding multiple files, e.g `testdata.yml|something-completely-different.py`? Thanks 😸

**Comment by 0atman** [comment]
@katstevens oh is it? Amazing! I'm finally picking up this project, this'll be a low-hanging fruit to add to the readme, thanks!
