### ISSUE TITLE
NEW PLAN: Vanilla pre-commit

### ISSUE THREAD

**Issue by 0atman** [alphagov/gds-pre-commit#81]
OK EVERYTHING IS TERRIBLE BURN IT DOWN.

Because it's so difficult to guess pythonpaths cross-platform, and we don't want a maintenance nightmare, I propose we let people install the vanilla pre-commit framework however they like. We can help them, but it's well-documented.

We then have a one liner `curl http://awesomesite/pre-commit-gds-customise.sh | sh` which:

- adds `os.environ["DETECT_SECRETS_SECURITY_TEAM"] = "in #cyber-security-help"` to the precommit framework generated hook 
- Sends us a ping saying "install done"

COOL? Cool.
![cover3](https://user-images.githubusercontent.com/114097/93081960-ff273980-f687-11ea-9b0d-536581dd4598.jpg)

**Comment by akinnane** [comment]
Looks like a good plan.

**Comment by danjoneslf** [comment]
Does this solve the pyenv / venv problems?

**Comment by 0atman** [comment]
@danjoneslf sure does. The pre-commit framework is very clever for cross-platform use. By hard-coding our own hook, we were losing a lot of that cleverness.

**Comment by danjoneslf** [comment]
I'm not sure I understand the value of this bit in that case. All it does is customise some help text and directs them to a google form? Is that worth doing? That just sounds like a couple of sentences of docs.

**Comment by 0atman** [comment]
@akinnane could you answer Dan's question?

**Comment by akinnane** [comment]
I agree with @danjoneslf, we don't really need to provide a wrapper script for this as developers should be able to follow the install guides for those tools themselves. Maybe if we document any rough edges it will be enough to easy people through it. Also I'd prefer not to maintain any more code than is needed.

**Comment by 0atman** [comment]
To be clear, the script adds a line to the hook script, and pings us an installation record, after they've installed everything themselves.

I agree we might not need to do it, but it's not a wrapper script.

I'd suggest this could be a function on the gds cli. `gds install-pre-commit` or similar, trivially.

**Comment by akinnane** [comment]
I'm not sure if the gds cli have a high enough adoption rate to warrant the integration.
